### ISSUE TITLE
Add example of using DbMigrationGenerator

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health-demo#207]
See also https://github.com/mfvanek/pg-index-health-demo/blob/71923ca3df79cc20d66a92e2bfdd9e504c3976d5/src/main/java/io/github/mfvanek/pg/index/health/demo/DemoApp.java#L48
and
https://github.com/mfvanek/pg-index-health/blob/54d1575c4dce19e494fba99150fc0670fd71dbb6/src/main/java/io/github/mfvanek/pg/generator/DbMigrationGenerator.java#L24

**Comment by marijarin** [comment]
Hello, I'd like to work on this issue.

**Comment by mfvanek** [comment]
Hi @marijarin !
Please take a look at https://github.com/mfvanek/pg-index-health-demo/blob/9f146547d47fff0682bc20bdc3cfe1504d0cbbba/pg-index-health-demo-without-spring/src/main/java/io/github/mfvanek/pg/index/health/demo/DemoApp.java#L40

The aim of this issue is to add similar functionality to the Spring Boot application.
You may implement a new POST endpoint - generateMigrationsAndApply (or something like that)
This endpoint may returns a DTO with next fileds:

- List<ForeignKey> foreignKeysBefore
- List<ForeignKey> foreignKeysAfter
- List<String> generatedMigrations
