### ISSUE TITLE
Set query timeout in application

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health-demo#242]
See

- https://github.com/spring-projects/spring-boot/issues/33866
- https://nameishari.medium.com/few-things-that-every-spring-boot-developer-should-know-jpa-edition-c746c36478db
- https://vladmihalcea.com/query-timeout-jpa-hibernate/

**Comment by marijarin** [comment]
Привет, я хотела бы поработать над этой issue

**Comment by mfvanek** [comment]
Hi @marijarin 
Yeah, sure! Feel free to contribute!

**Comment by mfvanek** [comment]
@marijarin 
Could you please add corresponding properties to repos?

- https://github.com/mfvanek/salary-calc
- https://github.com/mfvanek/spring-boot-open-telemetry-demo
- https://github.com/mfvanek/java-experiments

**Comment by marijarin** [comment]
OK, in a couple of days

**Comment by mfvanek** [comment]
@marijarin
I've merged 2 your PRs. Nice job!

**Comment by mfvanek** [comment]
@marijarin thanks a lot!
